name = "Spookslop"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fdc5cb959b2af220cad94261a235ec2a0cc82bbe1dc2ae60bebdc2ffcec8724"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.21.5"]
