name = "Spookslop"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f31163d28496b89843b3621e0c86ba9c23f6d6e852bd4026d337da8b1104c5aa"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.21.5"]
