name = "Spookslop"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b106e7736c0f52fdeb8b436f2eb6fedd0b8541691f21755faf91878d05897a9e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.21.5"]
