name = "Spookslop"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae089dfbbb315bc89cdaa25f49aaeaa037295da98532dd5f3c227354350ab0f8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.21.5"]
