name = "Spookslop"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6acd7711ffc44043d364612da869ab9d91b47a1364fd25f954f166bb6a897dc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.21.5"]
